# Configuration file containing necessary information in order to run the code

# Information on the used images
dataset:
    # Tile used for processing
    tile: "X16Y06"
    # Band pattern to select the images
    bandPattern: "NDVI_sm_ts.tif$"

# Information on the used folders
folders:
    # Input directory of the images
    NDVI_images: "../../../userdata3/NDVI_images/"
    # Directory for temporary objects
    temp: "../../../userdata3/tmp/"
    # Directory for output files
    outputDir: "../../../userdata3/output/"

# Section for training and classification
classification:
    # Ground truth data
    ground_truth: "../../../userdata3/TrainingData/TotalTrainingData_080617.csv"
    # Training data file
    training_variables: "../../../userdata3/TrainingData/TrainingData_variables.csv"
    # Harmonic metric data first two years (11-03-2014 -- 06-03-2016)
    metrics_2y: "../../../userdata3/output/harmonics/phase_amplitude.tif"
    # Harmonic metric data third year (11-03-2016 -- 06-03-2017)
    metrics_3y: "../../../userdata3/output/harmonics/phase_amplitude_3y.tif"
    # Class names, must be in alphabetical order
    classes: [Bareland, Cropland, Forest, Grassland, Shrubland, Urban, Water]
    # Class codes, must correspond to the order of classes
    codes: [60, 40, 10, 30, 20, 50, 80]
    # Colors to assign to each class, order must correspond
    colors: [khaki4, gold, darkgreen, lawngreen, purple, red, blue]
    # Filepath to accuracy statistics csv file of the basemap
    accStats_basemap: "../../../userdata3/output/classification/accuracyStats_basemap.csv"

# Information needed for change detection
changeDetection:
    # Illogical changes matrix (0 is logical change, 1 is illogical change)
    changeMatrix: [0,1,1,1,1,0,1,
                   0,0,0,0,0,0,1,
                   1,0,0,0,0,0,1,
                   1,1,0,0,0,0,1,
                   1,1,0,0,0,0,1,
                   1,1,0,0,0,0,0,
                   1,1,1,1,1,0,0]
    rcNames: [10,20,30,40,50,60,80]
