# Configuration file containing necessary information in order to run the code

# Information on the used images
dataset:
    # Tile used for processing
    tile: "X16Y06"
    # Band pattern to select the images
    bandPattern: "NDVI_sm_ts.tif$"

# Information on the used folders
folders:
    # Input directory of the images
    NDVI_images: "../../../userdata3/NDVI_images/"
    # Directory for temporary objects
    temp: "../../../userdata3/tmp/"

# Information on the used filenames
filenames:
    #

# Section for training and classification
classification:
    # Training data file
    training_image: "../../../userdata3/TrainingData/TrainingData_variables.csv"
    # Class names, must be in alphabetical order
    classes: [Bareland, Cropland, Forest, Grassland, Shrubland, Urban, Water]
    # Class codes, must correspond to the order of classes
    codes: [60, 40, 10, 30, 20, 50, 80]
    # Colors to assign to each class, order must correspond
    colors: [khaki4, gold, darkgreen, lawngreen, purple, red, blue]

# Information needed for change detection
changeDetection:
    # Illogical changes matrix (0 is logical change, 1 is illogical change)
    changeMatrix: [0,1,1,1,1,0,1,
                   0,0,0,0,0,0,1,
                   1,0,0,0,0,0,1,
                   1,1,0,0,0,0,1,
                   1,1,0,0,0,0,1,
                   1,1,0,0,0,0,0,
                   1,1,1,1,1,0,0]
    rcNames: [10,20,30,40,50,60,80]
